version: '3'

services:
  run-fortran-pypy:
    build:
      context: .
      args:
        - IMAGE_NAME=${PYPY_IMAGE_NAME}
        - IMAGE_VERSION=${PYPY_IMAGE_VERSION}
    image: lycantropos/run-fortran-pypy:1.0.0-alpha
    volumes:
      - ./README.md:/opt/run_fortran/README.md
      - ./requirements.txt:/opt/run_fortran/requirements.txt
      - ./run_fortran:/opt/run_fortran/run_fortran
      - ./setup.py:/opt/run_fortran/setup.py
      - ./test_project:/opt/run_fortran/test_project
    command:
      - run
      - -o
      - result
      - /opt/run_fortran/test_project
